<?php
/**
 * Admins detail — generated by tools/make-web-page.php
 *
 * Shows a single record from the `admins` table by id.
 */

$configPath = __DIR__ . '/../config.php';
$config = file_exists($configPath)
    ? require $configPath
    : (file_exists(__DIR__ . '/../config.example.php') ? require __DIR__ . '/../config.example.php' : []);

if (is_array($config) && !empty($config['timezone'])) {
    date_default_timezone_set($config['timezone']);
}

require_once __DIR__ . '/../controllers/api.controller.php';

$baseUrl  = (is_array($config) && isset($config['site']['base_url'])) ? rtrim($config['site']['base_url'], '/') . '/' : '/';
$siteName = (is_array($config) && isset($config['site']['name']))     ? $config['site']['name'] : 'My Website';

$table       = 'admins';
$idColumn    = 'id_admin';
$titleColumn = 'title_admin';
$listUrl     = $baseUrl . 'pages/' . 'prueba' . '.php';

$record   = null;
$error    = null;
$recordId = isset($_GET['id']) ? $_GET['id'] : null;

if ($recordId === null || $recordId === '') {
    $error = 'No record specified.';
} else {
    try {
        $response = ApiController::getById($table, $recordId, $idColumn);
        if ($response->status == 200 && !empty($response->results)) {
            $record = (array) $response->results[0];
        } else {
            $error = 'Record not found.';
        }
    } catch (Exception $e) {
        $error = 'Could not load the record.';
    }
}

$pageTitle       = ($record && isset($record[$titleColumn]) ? $record[$titleColumn] : 'Admins') . ' - ' . $siteName;
$pageDescription = 'Admins' . ' detail';

ob_start();
?>
<div class="container my-5">
    <p><a href="<?php echo htmlspecialchars($listUrl, ENT_QUOTES); ?>">&larr; Back to list</a></p>

    <?php if ($error): ?>
        <div class="alert alert-warning"><?php echo htmlspecialchars($error, ENT_QUOTES); ?></div>
    <?php else: ?>
        <h1 class="mb-4"><?php echo htmlspecialchars((string) ($record[$titleColumn] ?? 'Detail'), ENT_QUOTES); ?></h1>
        <table class="table">
            <tbody>
                <?php foreach ($record as $field => $value):
                    // Scalars render as-is; arrays/objects (e.g. JSON columns)
                    // are pretty-printed instead of crashing on a string cast.
                    $display = (is_scalar($value) || $value === null)
                        ? (string) $value
                        : json_encode($value, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT);
                ?>
                    <tr>
                        <th class="text-muted" style="width: 30%"><?php echo htmlspecialchars(ucwords(str_replace('_', ' ', $field)), ENT_QUOTES); ?></th>
                        <td><?php echo nl2br(htmlspecialchars($display, ENT_QUOTES)); ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    <?php endif; ?>
</div>
<?php
$pageContent = ob_get_clean();
include __DIR__ . '/../views/template.php';
