<?php
/**
 * Admins — generated by tools/make-web-page.php
 *
 * Lists records from the `admins` table. Adjust the markup as needed.
 */

$configPath = __DIR__ . '/../config.php';
$config = file_exists($configPath)
    ? require $configPath
    : (file_exists(__DIR__ . '/../config.example.php') ? require __DIR__ . '/../config.example.php' : []);

if (is_array($config) && !empty($config['timezone'])) {
    date_default_timezone_set($config['timezone']);
}

require_once __DIR__ . '/../controllers/api.controller.php';

$baseUrl  = (is_array($config) && isset($config['site']['base_url'])) ? rtrim($config['site']['base_url'], '/') . '/' : '/';
$siteName = (is_array($config) && isset($config['site']['name']))     ? $config['site']['name'] : 'My Website';

$pageTitle       = 'Admins' . ' - ' . $siteName;
$pageDescription = 'Admins' . ' listing';

$table       = 'admins';
$idColumn    = 'id_admin';
$titleColumn = 'title_admin';
$detailUrl   = $baseUrl . 'pages/' . 'prueba-detail' . '.php';

$records = [];
$error   = null;

try {
    $response = ApiController::getAll($table, '*', $idColumn, 'DESC', 0, 50);
    if ($response->status == 200) {
        $records = $response->results;
    } elseif ($response->status != 404) {
        $error = 'Could not load data.';
    }
} catch (Exception $e) {
    $error = 'Could not load data.';
}

ob_start();
?>
<div class="container my-5">
    <h1 class="mb-4"><?php echo htmlspecialchars($pageTitle, ENT_QUOTES); ?></h1>

    <?php if ($error): ?>
        <div class="alert alert-warning"><?php echo htmlspecialchars($error, ENT_QUOTES); ?></div>
    <?php elseif (empty($records)): ?>
        <div class="alert alert-info">No records yet.</div>
    <?php else: ?>
        <div class="row">
            <?php foreach ($records as $record):
                $row   = (array) $record;
                $id    = $row[$idColumn] ?? null;
                $title = $row[$titleColumn] ?? '';
            ?>
                <div class="col-md-6 col-lg-4 mb-4">
                    <div class="card h-100">
                        <div class="card-body">
                            <h5 class="card-title"><?php echo htmlspecialchars((string) $title, ENT_QUOTES); ?></h5>
                            <dl class="row small mb-0">
                                <?php foreach ($row as $field => $value):
                                    // Skip the id/title (already shown) and non-scalar values
                                    // (e.g. JSON columns) which can't be cast to a string.
                                    if ($field === $idColumn || $field === $titleColumn || $value === null || $value === '' || !is_scalar($value)) { continue; }
                                ?>
                                    <dt class="col-5 text-muted"><?php echo htmlspecialchars(ucwords(str_replace('_', ' ', $field)), ENT_QUOTES); ?></dt>
                                    <dd class="col-7"><?php echo htmlspecialchars(mb_strimwidth((string) $value, 0, 80, '…'), ENT_QUOTES); ?></dd>
                                <?php endforeach; ?>
                            </dl>
                        </div>
                        <?php if ($id !== null): ?>
                            <div class="card-footer">
                                <a class="btn btn-sm btn-primary" href="<?php echo htmlspecialchars($detailUrl . '?id=' . urlencode((string) $id), ENT_QUOTES); ?>">View details</a>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
</div>
<?php
$pageContent = ob_get_clean();
include __DIR__ . '/../views/template.php';
