<?php
/**
 * Web page generator
 *
 * Scaffolds public frontend pages for a dynamic table: a listing page
 * (web/pages/<name>.php) showing each record's fields with a link to a
 * detail page (web/pages/<name>-detail.php?id=...), following the project's
 * conventions (ApiController + the shared template, all output escaped).
 * This automates what previously had to be hand-written, mirroring the CMS's
 * table builder.
 *
 * Usage:
 *   php tools/make-web-page.php <table> [options]
 *
 * Options:
 *   --suffix=<s>   Column suffix (default: derived from <table>, e.g. "products" -> "product")
 *   --title=<col>  Column used as the card title (default: name_<suffix>)
 *   --id=<col>     Primary-key column (default: id_<suffix>)
 *   --name=<file>  Output file name without extension (default: <table>)
 *   --force        Overwrite the output file if it already exists
 *   --stdout       Print the generated page to stdout instead of writing a file
 *
 * Example:
 *   php tools/make-web-page.php products --suffix=product --title=name_product
 */

/**
 * Build the PHP source of a listing page. Pure function (no I/O) so it can be
 * unit-tested.
 *
 * @param array $opts table, suffix, idColumn, titleColumn, titlePlural
 * @return string
 */
function buildWebPageSource(array $opts) {
    $table       = $opts['table'];
    $idColumn    = $opts['idColumn'];
    $titleColumn = $opts['titleColumn'];
    $titlePlural = $opts['titlePlural'];

    // Values are validated identifiers / plain words, but encode defensively
    // so the generated file can never be broken by an odd input.
    $t  = var_export($table, true);
    $id = var_export($idColumn, true);
    $ti = var_export($titleColumn, true);
    $tp = var_export($titlePlural, true);
    $df = var_export($opts['detailFile'], true);

    return <<<PHP
<?php
/**
 * {$titlePlural} — generated by tools/make-web-page.php
 *
 * Lists records from the `{$table}` table. Adjust the markup as needed.
 */

\$configPath = __DIR__ . '/../config.php';
\$config = file_exists(\$configPath)
    ? require \$configPath
    : (file_exists(__DIR__ . '/../config.example.php') ? require __DIR__ . '/../config.example.php' : []);

if (is_array(\$config) && !empty(\$config['timezone'])) {
    date_default_timezone_set(\$config['timezone']);
}

require_once __DIR__ . '/../controllers/api.controller.php';

\$baseUrl  = (is_array(\$config) && isset(\$config['site']['base_url'])) ? rtrim(\$config['site']['base_url'], '/') . '/' : '/';
\$siteName = (is_array(\$config) && isset(\$config['site']['name']))     ? \$config['site']['name'] : 'My Website';

\$pageTitle       = {$tp} . ' - ' . \$siteName;
\$pageDescription = {$tp} . ' listing';

\$table       = {$t};
\$idColumn    = {$id};
\$titleColumn = {$ti};
\$detailUrl   = \$baseUrl . 'pages/' . {$df} . '.php';

\$records = [];
\$error   = null;

try {
    \$response = ApiController::getAll(\$table, '*', \$idColumn, 'DESC', 0, 50);
    if (\$response->status == 200) {
        \$records = \$response->results;
    } elseif (\$response->status != 404) {
        \$error = 'Could not load data.';
    }
} catch (Exception \$e) {
    \$error = 'Could not load data.';
}

ob_start();
?>
<div class="container my-5">
    <h1 class="mb-4"><?php echo htmlspecialchars(\$pageTitle, ENT_QUOTES); ?></h1>

    <?php if (\$error): ?>
        <div class="alert alert-warning"><?php echo htmlspecialchars(\$error, ENT_QUOTES); ?></div>
    <?php elseif (empty(\$records)): ?>
        <div class="alert alert-info">No records yet.</div>
    <?php else: ?>
        <div class="row">
            <?php foreach (\$records as \$record):
                \$row   = (array) \$record;
                \$id    = \$row[\$idColumn] ?? null;
                \$title = \$row[\$titleColumn] ?? '';
            ?>
                <div class="col-md-6 col-lg-4 mb-4">
                    <div class="card h-100">
                        <div class="card-body">
                            <h5 class="card-title"><?php echo htmlspecialchars((string) \$title, ENT_QUOTES); ?></h5>
                            <dl class="row small mb-0">
                                <?php foreach (\$row as \$field => \$value):
                                    // Skip the id/title (already shown) and non-scalar values
                                    // (e.g. JSON columns) which can't be cast to a string.
                                    if (\$field === \$idColumn || \$field === \$titleColumn || \$value === null || \$value === '' || !is_scalar(\$value)) { continue; }
                                ?>
                                    <dt class="col-5 text-muted"><?php echo htmlspecialchars(ucwords(str_replace('_', ' ', \$field)), ENT_QUOTES); ?></dt>
                                    <dd class="col-7"><?php echo htmlspecialchars(mb_strimwidth((string) \$value, 0, 80, '…'), ENT_QUOTES); ?></dd>
                                <?php endforeach; ?>
                            </dl>
                        </div>
                        <?php if (\$id !== null): ?>
                            <div class="card-footer">
                                <a class="btn btn-sm btn-primary" href="<?php echo htmlspecialchars(\$detailUrl . '?id=' . urlencode((string) \$id), ENT_QUOTES); ?>">View details</a>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
</div>
<?php
\$pageContent = ob_get_clean();
include __DIR__ . '/../views/template.php';

PHP;
}

/**
 * Build the PHP source of a single-record detail page. Pure function (no I/O).
 *
 * @param array $opts table, idColumn, titleColumn, titlePlural, fileName
 * @return string
 */
function buildDetailPageSource(array $opts) {
    $table       = $opts['table'];
    $titlePlural = $opts['titlePlural'];

    $t  = var_export($table, true);
    $id = var_export($opts['idColumn'], true);
    $ti = var_export($opts['titleColumn'], true);
    $tp = var_export($titlePlural, true);
    $lf = var_export($opts['fileName'], true);

    return <<<PHP
<?php
/**
 * {$titlePlural} detail — generated by tools/make-web-page.php
 *
 * Shows a single record from the `{$table}` table by id.
 */

\$configPath = __DIR__ . '/../config.php';
\$config = file_exists(\$configPath)
    ? require \$configPath
    : (file_exists(__DIR__ . '/../config.example.php') ? require __DIR__ . '/../config.example.php' : []);

if (is_array(\$config) && !empty(\$config['timezone'])) {
    date_default_timezone_set(\$config['timezone']);
}

require_once __DIR__ . '/../controllers/api.controller.php';

\$baseUrl  = (is_array(\$config) && isset(\$config['site']['base_url'])) ? rtrim(\$config['site']['base_url'], '/') . '/' : '/';
\$siteName = (is_array(\$config) && isset(\$config['site']['name']))     ? \$config['site']['name'] : 'My Website';

\$table       = {$t};
\$idColumn    = {$id};
\$titleColumn = {$ti};
\$listUrl     = \$baseUrl . 'pages/' . {$lf} . '.php';

\$record   = null;
\$error    = null;
\$recordId = isset(\$_GET['id']) ? \$_GET['id'] : null;

if (\$recordId === null || \$recordId === '') {
    \$error = 'No record specified.';
} else {
    try {
        \$response = ApiController::getById(\$table, \$recordId, \$idColumn);
        if (\$response->status == 200 && !empty(\$response->results)) {
            \$record = (array) \$response->results[0];
        } else {
            \$error = 'Record not found.';
        }
    } catch (Exception \$e) {
        \$error = 'Could not load the record.';
    }
}

\$pageTitle       = (\$record && isset(\$record[\$titleColumn]) ? \$record[\$titleColumn] : {$tp}) . ' - ' . \$siteName;
\$pageDescription = {$tp} . ' detail';

ob_start();
?>
<div class="container my-5">
    <p><a href="<?php echo htmlspecialchars(\$listUrl, ENT_QUOTES); ?>">&larr; Back to list</a></p>

    <?php if (\$error): ?>
        <div class="alert alert-warning"><?php echo htmlspecialchars(\$error, ENT_QUOTES); ?></div>
    <?php else: ?>
        <h1 class="mb-4"><?php echo htmlspecialchars((string) (\$record[\$titleColumn] ?? 'Detail'), ENT_QUOTES); ?></h1>
        <table class="table">
            <tbody>
                <?php foreach (\$record as \$field => \$value):
                    // Scalars render as-is; arrays/objects (e.g. JSON columns)
                    // are pretty-printed instead of crashing on a string cast.
                    \$display = (is_scalar(\$value) || \$value === null)
                        ? (string) \$value
                        : json_encode(\$value, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT);
                ?>
                    <tr>
                        <th class="text-muted" style="width: 30%"><?php echo htmlspecialchars(ucwords(str_replace('_', ' ', \$field)), ENT_QUOTES); ?></th>
                        <td><?php echo nl2br(htmlspecialchars(\$display, ENT_QUOTES)); ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    <?php endif; ?>
</div>
<?php
\$pageContent = ob_get_clean();
include __DIR__ . '/../views/template.php';

PHP;
}

/**
 * Validate a value is a safe SQL/identifier-style token.
 */
function mwp_isIdentifier($name) {
    return is_string($name) && preg_match('/^[a-zA-Z0-9_]+$/', $name) === 1;
}

/**
 * Derive a singular suffix from a table name (very small heuristic).
 */
function mwp_deriveSuffix($table) {
    if (substr($table, -3) === 'ies') {            // categories -> category
        return substr($table, 0, -3) . 'y';
    }
    if (substr($table, -1) === 's' && substr($table, -2) !== 'ss') {
        return substr($table, 0, -1);              // products -> product
    }
    return $table;
}

/**
 * Build a human "Title Case Plural" from a table name.
 */
function mwp_titleize($table) {
    return ucwords(str_replace('_', ' ', $table));
}

/**
 * Resolve CLI options into the generator option array. Throws on bad input.
 */
function mwp_resolveOptions($table, array $flags) {
    if (!mwp_isIdentifier($table)) {
        throw new InvalidArgumentException("Invalid table name: '{$table}' (use letters, digits and underscores).");
    }

    $suffix      = (isset($flags['suffix']) && is_string($flags['suffix'])) ? $flags['suffix'] : mwp_deriveSuffix($table);
    $idColumn    = (isset($flags['id'])     && is_string($flags['id']))     ? $flags['id']     : ('id_' . $suffix);
    $titleColumn = (isset($flags['title'])  && is_string($flags['title']))  ? $flags['title']  : ('name_' . $suffix);

    foreach (['suffix' => $suffix, 'id' => $idColumn, 'title' => $titleColumn] as $label => $val) {
        if (!mwp_isIdentifier($val)) {
            throw new InvalidArgumentException("Invalid {$label}: '{$val}'.");
        }
    }

    $fileName = (isset($flags['name']) && is_string($flags['name'])) ? $flags['name'] : $table;
    if (!preg_match('/^[a-zA-Z0-9_-]+$/', $fileName)) {
        throw new InvalidArgumentException("Invalid output file name: '{$fileName}'.");
    }

    return [
        'table'       => $table,
        'suffix'      => $suffix,
        'idColumn'    => $idColumn,
        'titleColumn' => $titleColumn,
        'titlePlural' => mwp_titleize($table),
        'fileName'    => $fileName,
        'detailFile'  => $fileName . '-detail',
    ];
}

// ---------------------------------------------------------------------------
// CLI entry point (skipped when this file is required from tests).
// ---------------------------------------------------------------------------
if (PHP_SAPI === 'cli' && isset($argv) && realpath($argv[0]) === realpath(__FILE__)) {

    $args  = array_slice($argv, 1);
    $table = null;
    $flags = [];

    foreach ($args as $arg) {
        if (strpos($arg, '--') === 0) {
            $kv = explode('=', substr($arg, 2), 2);
            $flags[$kv[0]] = $kv[1] ?? true;
        } elseif ($table === null) {
            $table = $arg;
        }
    }

    if ($table === null || isset($flags['help'])) {
        fwrite(STDOUT, "Usage: php tools/make-web-page.php <table> [--suffix= --title= --id= --name= --no-detail --force --stdout]\n");
        exit($table === null ? 1 : 0);
    }

    try {
        $opts = mwp_resolveOptions($table, $flags);
    } catch (InvalidArgumentException $e) {
        fwrite(STDERR, "Error: " . $e->getMessage() . "\n");
        exit(1);
    }

    $withDetail = !isset($flags['no-detail']);

    // Build the list page and, unless --no-detail, the detail page.
    $targets = [['file' => $opts['fileName'], 'source' => buildWebPageSource($opts)]];
    if ($withDetail) {
        $targets[] = ['file' => $opts['detailFile'], 'source' => buildDetailPageSource($opts)];
    }

    if (isset($flags['stdout'])) {
        foreach ($targets as $tgt) {
            fwrite(STDOUT, "===== web/pages/{$tgt['file']}.php =====\n");
            fwrite(STDOUT, $tgt['source'] . "\n");
        }
        exit(0);
    }

    // Refuse if any target exists (unless --force), before writing anything.
    foreach ($targets as $tgt) {
        $path = __DIR__ . '/../web/pages/' . $tgt['file'] . '.php';
        if (file_exists($path) && !isset($flags['force'])) {
            fwrite(STDERR, "Error: {$path} already exists. Use --force to overwrite.\n");
            exit(1);
        }
    }

    foreach ($targets as $tgt) {
        $path = __DIR__ . '/../web/pages/' . $tgt['file'] . '.php';
        if (@file_put_contents($path, $tgt['source']) === false) {
            fwrite(STDERR, "Error: could not write {$path} (check permissions).\n");
            exit(1);
        }
        fwrite(STDOUT, "Created web/pages/{$tgt['file']}.php\n");
    }

    fwrite(STDOUT, "Done — table '{$opts['table']}'" . ($withDetail ? " (list + detail)." : " (list).") . "\n");
    exit(0);
}
