<?php
/**
 * Web page generator
 *
 * Scaffolds a public frontend listing page (web/pages/<name>.php) for a
 * dynamic table, following the project's conventions (ApiController + the
 * shared template, all output escaped). This automates what previously had
 * to be hand-written for every table, mirroring the CMS's table builder.
 *
 * Usage:
 *   php tools/make-web-page.php <table> [options]
 *
 * Options:
 *   --suffix=<s>   Column suffix (default: derived from <table>, e.g. "products" -> "product")
 *   --title=<col>  Column used as the card title (default: name_<suffix>)
 *   --id=<col>     Primary-key column (default: id_<suffix>)
 *   --name=<file>  Output file name without extension (default: <table>)
 *   --force        Overwrite the output file if it already exists
 *   --stdout       Print the generated page to stdout instead of writing a file
 *
 * Example:
 *   php tools/make-web-page.php products --suffix=product --title=name_product
 */

/**
 * Build the PHP source of a listing page. Pure function (no I/O) so it can be
 * unit-tested.
 *
 * @param array $opts table, suffix, idColumn, titleColumn, titlePlural
 * @return string
 */
function buildWebPageSource(array $opts) {
    $table       = $opts['table'];
    $idColumn    = $opts['idColumn'];
    $titleColumn = $opts['titleColumn'];
    $titlePlural = $opts['titlePlural'];

    // Values are validated identifiers / plain words, but encode defensively
    // so the generated file can never be broken by an odd input.
    $t  = var_export($table, true);
    $id = var_export($idColumn, true);
    $ti = var_export($titleColumn, true);
    $tp = var_export($titlePlural, true);

    return <<<PHP
<?php
/**
 * {$titlePlural} — generated by tools/make-web-page.php
 *
 * Lists records from the `{$table}` table. Adjust the markup as needed.
 */

\$configPath = __DIR__ . '/../config.php';
\$config = file_exists(\$configPath)
    ? require \$configPath
    : (file_exists(__DIR__ . '/../config.example.php') ? require __DIR__ . '/../config.example.php' : []);

if (is_array(\$config) && !empty(\$config['timezone'])) {
    date_default_timezone_set(\$config['timezone']);
}

require_once __DIR__ . '/../controllers/api.controller.php';

\$baseUrl  = (is_array(\$config) && isset(\$config['site']['base_url'])) ? rtrim(\$config['site']['base_url'], '/') . '/' : '/';
\$siteName = (is_array(\$config) && isset(\$config['site']['name']))     ? \$config['site']['name'] : 'My Website';

\$pageTitle       = {$tp} . ' - ' . \$siteName;
\$pageDescription = {$tp} . ' listing';

\$table       = {$t};
\$idColumn    = {$id};
\$titleColumn = {$ti};

\$records = [];
\$error   = null;

try {
    \$response = ApiController::getAll(\$table, '*', \$idColumn, 'DESC', 0, 50);
    if (\$response->status == 200) {
        \$records = \$response->results;
    } elseif (\$response->status != 404) {
        \$error = 'Could not load data.';
    }
} catch (Exception \$e) {
    \$error = 'Could not load data.';
}

ob_start();
?>
<div class="container my-5">
    <h1 class="mb-4"><?php echo htmlspecialchars(\$pageTitle, ENT_QUOTES); ?></h1>

    <?php if (\$error): ?>
        <div class="alert alert-warning"><?php echo htmlspecialchars(\$error, ENT_QUOTES); ?></div>
    <?php elseif (empty(\$records)): ?>
        <div class="alert alert-info">No records yet.</div>
    <?php else: ?>
        <div class="row">
            <?php foreach (\$records as \$record):
                \$row   = (array) \$record;
                \$id    = \$row[\$idColumn] ?? null;
                \$title = \$row[\$titleColumn] ?? '';
            ?>
                <div class="col-md-6 col-lg-4 mb-4">
                    <div class="card h-100">
                        <div class="card-body">
                            <h5 class="card-title"><?php echo htmlspecialchars(\$title, ENT_QUOTES); ?></h5>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
</div>
<?php
\$pageContent = ob_get_clean();
include __DIR__ . '/../views/template.php';

PHP;
}

/**
 * Validate a value is a safe SQL/identifier-style token.
 */
function mwp_isIdentifier($name) {
    return is_string($name) && preg_match('/^[a-zA-Z0-9_]+$/', $name) === 1;
}

/**
 * Derive a singular suffix from a table name (very small heuristic).
 */
function mwp_deriveSuffix($table) {
    if (substr($table, -3) === 'ies') {            // categories -> category
        return substr($table, 0, -3) . 'y';
    }
    if (substr($table, -1) === 's' && substr($table, -2) !== 'ss') {
        return substr($table, 0, -1);              // products -> product
    }
    return $table;
}

/**
 * Build a human "Title Case Plural" from a table name.
 */
function mwp_titleize($table) {
    return ucwords(str_replace('_', ' ', $table));
}

/**
 * Resolve CLI options into the generator option array. Throws on bad input.
 */
function mwp_resolveOptions($table, array $flags) {
    if (!mwp_isIdentifier($table)) {
        throw new InvalidArgumentException("Invalid table name: '{$table}' (use letters, digits and underscores).");
    }

    $suffix      = $flags['suffix'] ?? mwp_deriveSuffix($table);
    $idColumn    = $flags['id']     ?? ('id_' . $suffix);
    $titleColumn = $flags['title']  ?? ('name_' . $suffix);

    foreach (['suffix' => $suffix, 'id' => $idColumn, 'title' => $titleColumn] as $label => $val) {
        if (!mwp_isIdentifier($val)) {
            throw new InvalidArgumentException("Invalid {$label}: '{$val}'.");
        }
    }

    return [
        'table'       => $table,
        'suffix'      => $suffix,
        'idColumn'    => $idColumn,
        'titleColumn' => $titleColumn,
        'titlePlural' => mwp_titleize($table),
    ];
}

// ---------------------------------------------------------------------------
// CLI entry point (skipped when this file is required from tests).
// ---------------------------------------------------------------------------
if (PHP_SAPI === 'cli' && isset($argv) && realpath($argv[0]) === realpath(__FILE__)) {

    $args  = array_slice($argv, 1);
    $table = null;
    $flags = [];

    foreach ($args as $arg) {
        if (strpos($arg, '--') === 0) {
            $kv = explode('=', substr($arg, 2), 2);
            $flags[$kv[0]] = $kv[1] ?? true;
        } elseif ($table === null) {
            $table = $arg;
        }
    }

    if ($table === null || isset($flags['help'])) {
        fwrite(STDOUT, "Usage: php tools/make-web-page.php <table> [--suffix= --title= --id= --name= --force --stdout]\n");
        exit($table === null ? 1 : 0);
    }

    try {
        $opts = mwp_resolveOptions($table, $flags);
    } catch (InvalidArgumentException $e) {
        fwrite(STDERR, "Error: " . $e->getMessage() . "\n");
        exit(1);
    }

    $source = buildWebPageSource($opts);

    if (isset($flags['stdout'])) {
        fwrite(STDOUT, $source);
        exit(0);
    }

    $fileName = isset($flags['name']) && is_string($flags['name']) ? $flags['name'] : $table;
    if (!preg_match('/^[a-zA-Z0-9_-]+$/', $fileName)) {
        fwrite(STDERR, "Error: invalid output file name '{$fileName}'.\n");
        exit(1);
    }

    $target = __DIR__ . '/../web/pages/' . $fileName . '.php';
    if (file_exists($target) && !isset($flags['force'])) {
        fwrite(STDERR, "Error: {$target} already exists. Use --force to overwrite.\n");
        exit(1);
    }

    if (@file_put_contents($target, $source) === false) {
        fwrite(STDERR, "Error: could not write {$target} (check permissions).\n");
        exit(1);
    }

    fwrite(STDOUT, "Created web/pages/{$fileName}.php for table '{$table}'.\n");
    fwrite(STDOUT, "Open it at: <site>/web/pages/{$fileName}.php\n");
    exit(0);
}
