<?php
/**
 * Project setup / bootstrap.
 *
 * Idempotent. Run after installing or restoring a backup to make sure the
 * instance has its config files and writable directories. Intended to be run
 * by setup.sh (which also fixes ownership/permissions), but works standalone:
 *
 *     php tools/setup.php
 *
 * What it does:
 *   - Creates config.php from config.example.php for cms/, web/ and each plugin
 *     (only when missing — never overwrites a real config).
 *   - Specifically generates a WORKING web/config.php by reusing the API
 *     base_url + key from cms/config.php (the public site and the CMS talk to
 *     the same API), deriving the public site base_url from it.
 *   - Ensures the writable directories exist.
 *
 * It does NOT change ownership/permissions (PHP can't), and never prints secrets.
 */

$root = dirname(__DIR__);
$created = [];
$skipped = [];

function out($m) { fwrite(STDOUT, $m . PHP_EOL); }

/* ---------------------------------------------------------------------------
 * 1. Writable directories
 * ------------------------------------------------------------------------- */
$writableDirs = ['web/pages', 'logs', 'api/tmp', 'cms/views/assets/files', 'packages'];
foreach ($writableDirs as $rel) {
    $dir = $root . '/' . $rel;
    if (!is_dir($dir)) {
        if (@mkdir($dir, 0775, true)) {
            @chmod($dir, 0775); // mkdir is subject to umask; enforce 0775
            $created[] = $rel . '/';
        }
    }
}

/* ---------------------------------------------------------------------------
 * 2. config.php from config.example.php (cms, web, plugins) — only if missing
 * ------------------------------------------------------------------------- */
$configDirs = array_merge([$root . '/cms', $root . '/web'], glob($root . '/plugins/*', GLOB_ONLYDIR) ?: []);
foreach ($configDirs as $dir) {
    $example = $dir . '/config.example.php';
    $config  = $dir . '/config.php';
    if (file_exists($example) && !file_exists($config)) {
        // web/config.php is generated from cms below; skip the plain copy here.
        if ($dir === $root . '/web') {
            continue;
        }
        if (@copy($example, $config)) {
            $created[] = str_replace($root . '/', '', $config);
        } else {
            out('! Could not create ' . str_replace($root . '/', '', $config) . ' (permission? run via setup.sh / sudo).');
        }
    } elseif (file_exists($config)) {
        $skipped[] = str_replace($root . '/', '', $config) . ' (already exists)';
    }
}

/* ---------------------------------------------------------------------------
 * 3. web/config.php — generate a working file from cms/config.php
 * ------------------------------------------------------------------------- */
$webConfig = $root . '/web/config.php';
$cmsConfig = file_exists($root . '/cms/config.php') ? @include $root . '/cms/config.php' : null;

if (!file_exists($webConfig)) {
    if (is_array($cmsConfig) && !empty($cmsConfig['api']['base_url']) && !empty($cmsConfig['api']['key'])) {
        $apiBase  = rtrim($cmsConfig['api']['base_url'], '/');
        // The public site usually sits next to the API (…/api → …/web). If that
        // shape doesn't apply (subdomain / different host), warn so the user
        // sets site.base_url manually.
        $siteBase = preg_replace('#/api$#', '/web', $apiBase);
        if ($siteBase === $apiBase) {
            out('! Could not derive the public site URL from api.base_url (' . $apiBase . ').');
            out('  Edit web/config.php and set site.base_url to your public web URL.');
        }
        $siteBase = rtrim($siteBase, '/') . '/';
        $data = [
            'api' => [
                'base_url' => $apiBase . '/',
                'key'      => $cmsConfig['api']['key'],
            ],
            'site' => [
                'name'        => 'My Website',
                'title'       => 'My Website',
                'description' => '',
                'base_url'    => $siteBase,
            ],
            'timezone' => $cmsConfig['timezone'] ?? 'UTC',
        ];
        $php = "<?php\n"
             . "// Generated by tools/setup.php from cms/config.php. Edit as needed.\n"
             . "if (basename(\$_SERVER['PHP_SELF']) === 'config.php') { http_response_code(403); die('Forbidden'); }\n"
             . "return " . var_export($data, true) . ";\n";
        if (@file_put_contents($webConfig, $php) !== false) {
            $created[] = 'web/config.php (from cms/config.php)';
        } else {
            out('! Could not write web/config.php (permission?) — run via setup.sh / sudo.');
        }
    } else {
        out('! web/config.php not created: configure cms/config.php first (api.base_url + api.key).');
    }
} else {
    $skipped[] = 'web/config.php (already exists)';
}

/* ---------------------------------------------------------------------------
 * Summary
 * ------------------------------------------------------------------------- */
out('');
out('Setup summary');
out('-------------');
if ($created) {
    out('Created:');
    foreach ($created as $c) { out('  + ' . $c); }
} else {
    out('Nothing to create — everything already in place.');
}
if ($skipped) {
    out('Kept:');
    foreach ($skipped as $s) { out('  = ' . $s); }
}
out('');
out('Review the generated config.php files and fill any remaining secrets');
out('(database, email, payment keys, etc.).');
